### ISSUE TITLE
How to train cvaegan with caleba dataset？

### ISSUE THREAD

**Issue by Arthurzhangsheng** [Yoshiki-Watanabe/cvae-gan#3]
I follow the readme.md, and got the "celebB.hdf5" file, but it has some problem with "train_conditional.py", the original code is this
```
from datasets import load_data, mnist, svhn, hairdata, hairdata_4tags
```
but according to the file directory structure，I think it should be:
```
from datasets import mnist, svhn, hairdata, hairdata_4tags
from datasets.datasets import load_data
```

However, I still can't train it on celeba, I use this command
```
python train_conditional.py --model=cvaegan --epoch=200 --batchsize=100 --output=output --dataset=datasets/celebB.hdf5
```
but got a keyerror
```
(tf) F:\zs\cvae-gan>python train_conditional.py --model=cvaegan --epoch=200 --batchsize=100 --output=output --dataset=datasets/celebB.hdf5
Using TensorFlow backend.
Traceback (most recent call last):
  File "train_conditional.py", line 80, in <module>
    main()
  File "train_conditional.py", line 55, in main
    datasets = load_data(args.dataset)
  File "F:\zs\cvae-gan\datasets\datasets.py", line 56, in load_data
    dset.attrs = np.asarray(f['attrs'], 'float32')
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\zs\Anaconda3\envs\tf\lib\site-packages\h5py\_hl\group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'attrs' doesn't exist)"
```

So, could you teach me how to train cvaegan on celeba?

**Comment by Arthurzhangsheng** [comment]
OK，I solved this problem. because the key in  `datasets/create_celeba.py`  is different from the key in ` `datasets/datasets.py` `
modify `datasets/create_celeba.py` line 113-115:
```
    dset = h5.create_dataset('images', data=image_data, dtype='uint8')
    dset = h5.create_dataset('attr_names', data=label_names, dtype=string_dt)
    dset = h5.create_dataset('attrs', data=labels, dtype='uint8')
```
now the key names are the same.
